/* eslint-disable @typescript-eslint/no-unused-vars */
// noinspection ES6UnusedImports

import type { BedDTO, GridItemDTO } from "@groei/common/src/models/Bed.ts";
import {
  Month,
  PlantHeight,
  type SeedDTO,
} from "@groei/common/src/models/Seed.ts";
import type { User } from "@groei/common/src/models/User.ts";
import { db } from "./index.ts";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { seedsTable, usersTable } from "./schema.ts";

const main = async () => {
  const user: User = {
    name: "Janek",
    email: "ikben@janekozga.nl",
    avatar: "https://example.com/avatar.jpg",
  };

  const februarySeeds: SeedDTO[] = [
    {
      id: crypto.randomUUID(),
      name: "Tomaat",
      variety: "San Marzano 2",
      sowFrom: Month.February,
      sowTill: Month.March,
      plantFrom: Month.April,
      plantTill: Month.July,
      harvestFrom: Month.April,
      harvestTill: Month.October,
      plantHeight: PlantHeight.CLIMBER,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Peterselie",
      variety: "Gigante d'Italia",
      sowFrom: Month.February,
      sowTill: Month.March,
      plantFrom: Month.April,
      plantTill: Month.July,
      harvestFrom: Month.April,
      harvestTill: Month.October,
      expirationDate: "2024-01-07",
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 2,
    },
    {
      id: crypto.randomUUID(),
      name: "Witte Spitskool",
      variety: "Express",
      sowFrom: Month.February,
      sowTill: Month.March,
      plantFrom: Month.April,
      plantTill: Month.May,
      harvestFrom: Month.June,
      harvestTill: Month.October,
      expirationDate: "2027-01-07",
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Spinazie",
      variety: "Viroflex Winterreuzen",
      sowFrom: Month.February,
      sowTill: Month.November,
      plantFrom: Month.March,
      plantTill: Month.December,
      expirationDate: "2027-01-07",
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Tuinboon",
      variety: "Witkiem",
      sowFrom: Month.February,
      sowTill: Month.May,
      plantFrom: Month.February,
      plantTill: Month.May,
      harvestFrom: Month.June,
      harvestTill: Month.July,
      expirationDate: "2027-01-07",
      plantHeight: PlantHeight.CLIMBER,
      numberOfSeedsPerGridCell: 4,
      preSprout: true,
    },
    {
      id: crypto.randomUUID(),
      name: "Veldsla",
      variety: "Grote Noord Hollandse",
      sowFrom: Month.February,
      sowTill: Month.October,
      plantFrom: Month.February,
      plantTill: Month.October,
      expirationDate: "2024-01-01",
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Tomaat",
      variety: "Roma",
      sowFrom: Month.February,
      sowTill: Month.March,
      plantFrom: Month.April,
      plantTill: Month.July,
      harvestFrom: Month.April,
      harvestTill: Month.October,
      plantHeight: PlantHeight.CLIMBER,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Tomaat",
      variety: "Sweety",
      sowFrom: Month.February,
      sowTill: Month.March,
      plantFrom: Month.April,
      plantTill: Month.July,
      harvestFrom: Month.April,
      harvestTill: Month.October,
      plantHeight: PlantHeight.CLIMBER,
      numberOfSeedsPerGridCell: 1,
      expirationDate: "2024-01-01",
    },
    {
      id: crypto.randomUUID(),
      name: "Sugarsnap",
      variety: "Jessy",
      sowFrom: Month.February,
      sowTill: Month.July,
      plantFrom: Month.March,
      plantTill: Month.July,
      expirationDate: "2024-01-01",
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 9,
      preSprout: true,
    },
    {
      id: crypto.randomUUID(),
      name: "Wintererwt",
      variety: "Doperwt Feltham First",
      sowFrom: Month.February,
      sowTill: Month.July,
      plantFrom: Month.March,
      plantTill: Month.July,
      expirationDate: "2024-01-01",
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 9,
      preSprout: true,
    },
    {
      id: crypto.randomUUID(),
      name: "Broccoli",
      variety: "Calabrese Natalino",
      sowFrom: Month.February,
      sowTill: Month.April,
      plantFrom: Month.April,
      plantTill: Month.July,
      harvestFrom: Month.July,
      harvestTill: Month.November,
      expirationDate: "2025-01-07",
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Boerenkool",
      variety: "Westlandse Herfst Laat",
      sowFrom: Month.January,
      sowTill: Month.April,
      plantFrom: Month.April,
      plantTill: Month.June,
      harvestFrom: Month.November,
      harvestTill: Month.January,
      expirationDate: "2027-01-07",
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Radijs",
      variety: "Sparkler 2",
      sowFrom: Month.February,
      sowTill: Month.March,
      plantFrom: Month.March,
      plantTill: Month.August,
      harvestFrom: Month.May,
      harvestTill: Month.November,
      expirationDate: "2024-01-07",
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
  ] as SeedDTO[];

  const marchSeeds: SeedDTO[] = [
    {
      id: crypto.randomUUID(),
      name: "Kamille",
      variety: "",
      sowFrom: Month.March,
      sowTill: Month.June,
      plantFrom: Month.March,
      plantTill: Month.June,
      harvestFrom: Month.April,
      harvestTill: Month.October,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Aubergine",
      variety: "Black Beauty",
      sowFrom: Month.March,
      sowTill: Month.April,
      plantFrom: Month.March,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Prei",
      variety: "Winterreuzen 3",
      sowFrom: Month.March,
      sowTill: Month.May,
      plantFrom: Month.March,
      plantTill: Month.May,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Basilicum",
      variety: "Bascuro Darkgreen",
      sowFrom: Month.March,
      sowTill: Month.July,
      plantFrom: Month.May,
      plantTill: Month.July,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Majoraan",
      variety: "Majorana Hortensis",
      sowFrom: Month.March,
      sowTill: Month.July,
      plantFrom: Month.May,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Wortel",
      variety: "Zomer Nantes 2",
      sowFrom: Month.March,
      sowTill: Month.July,
      plantFrom: Month.March,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Tatsoi",
      variety: "Brassica Narinosa",
      sowFrom: Month.March,
      sowTill: Month.August,
      plantFrom: Month.March,
      plantTill: Month.August,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Spinazie",
      variety: "Viking",
      sowFrom: Month.March,
      sowTill: Month.October,
      plantFrom: Month.March,
      plantTill: Month.October,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Wintersla",
      variety: "Merveile D'hiver",
      sowFrom: Month.March,
      sowTill: Month.October,
      plantFrom: Month.March,
      plantTill: Month.October,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Rucola",
      variety: "Eruca Sativa",
      sowFrom: Month.March,
      sowTill: Month.October,
      plantFrom: Month.March,
      plantTill: Month.October,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Bindsla",
      variety: "Mini Little Gem",
      sowFrom: Month.March,
      sowTill: Month.September,
      plantFrom: Month.March,
      plantTill: Month.September,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Marjolein",
      variety: "Wilde / Oregano",
      sowFrom: Month.March,
      sowTill: Month.June,
      plantFrom: Month.March,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 2,
    },
    {
      id: crypto.randomUUID(),
      name: "Salie",
      variety: "Salvia officinialis",
      sowFrom: Month.March,
      sowTill: Month.June,
      plantFrom: Month.March,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      perennial: true,
      numberOfSeedsPerGridCell: 2,
    },
    {
      id: crypto.randomUUID(),
      name: "Maggikruid Lavas",
      variety: "Levisticum Officinale",
      sowFrom: Month.March,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.TALL,
      perennial: true,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Afrikaan Tagetes",
      variety: "Bonita",
      sowFrom: Month.March,
      sowTill: Month.May,
      plantFrom: Month.April,
      plantTill: Month.May,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Winterpostelein",
      variety: "Purslain",
      sowFrom: Month.March,
      sowTill: Month.October,
      plantFrom: Month.March,
      plantTill: Month.October,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Pluksla",
      variety: "Australische gele",
      sowFrom: Month.March,
      sowTill: Month.October,
      plantFrom: Month.March,
      plantTill: Month.October,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Bleekselderij",
      variety: "Goudgele zelfblekende 2",
      sowFrom: Month.February,
      sowTill: Month.May,
      plantFrom: Month.March,
      plantTill: Month.May,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Radijs",
      variety: "Ronde soorten gemengd",
      sowFrom: Month.March,
      sowTill: Month.August,
      plantFrom: Month.March,
      plantTill: Month.August,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Snijbiet",
      variety: "Bright Lights",
      sowFrom: Month.March,
      sowTill: Month.August,
      plantFrom: Month.March,
      plantTill: Month.August,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 4,
    },
  ] as SeedDTO[];

  const aprilSeeds = [
    {
      id: crypto.randomUUID(),
      name: "Eetbare bloemen",
      variety: "Mix",
      sowFrom: Month.March,
      sowTill: Month.June,
      plantFrom: Month.March,
      plantTill: Month.June,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 30,
    },
    {
      id: crypto.randomUUID(),
      name: "Courgette",
      variety: "Black Beauty",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Kalletes",
      variety: "Boerenkool Spruiten F1",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.TALL,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Dille",
      variety: "",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Stoksnijbonen",
      variety: "Helda",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.CLIMBER,
      numberOfSeedsPerGridCell: 2,
    },
    {
      id: crypto.randomUUID(),
      name: "Veldsla",
      variety: "Verte a couer plein 2",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Koolrapen",
      variety: "Champion",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Koolrapen",
      variety: "Champion",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Spruiten",
      variety: "Groninger",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.TALL,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Koriander",
      variety: "",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.TALL,
      numberOfSeedsPerGridCell: 9,
    },
    {
      id: crypto.randomUUID(),
      name: "Rode Biet",
      variety: "Kogel 5 Loki",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Zonnebloem",
      variety: "Evening Sun",
      sowFrom: Month.April,
      sowTill: Month.July,
      plantFrom: Month.April,
      plantTill: Month.July,
      plantHeight: PlantHeight.TALL,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Witte Kool",
      variety: "Langedijker Bewaar",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Komkommer",
      variety: "Marketmore",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.CLIMBER,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Bieslook",
      variety: "Commune",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 20,
    },
    {
      id: crypto.randomUUID(),
      name: "Basilicum",
      variety: "Kaneel, Cinnamon",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "NZ Spinazie",
      variety: "",
      sowFrom: Month.April,
      sowTill: Month.May,
      plantFrom: Month.April,
      plantTill: Month.May,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 2,
    },
    {
      id: crypto.randomUUID(),
      name: "Prei",
      variety: "De Carentan 2",
      sowFrom: Month.April,
      sowTill: Month.May,
      plantFrom: Month.April,
      plantTill: Month.May,
      plantHeight: PlantHeight.SHORT,
      numberOfSeedsPerGridCell: 4,
    },
    {
      id: crypto.randomUUID(),
      name: "Mais",
      variety: "Suikermais Tasty Sweet F1",
      sowFrom: Month.May,
      sowTill: Month.June,
      plantFrom: Month.May,
      plantTill: Month.June,
      plantHeight: PlantHeight.TALL,
      numberOfSeedsPerGridCell: 2,
    },
    {
      id: crypto.randomUUID(),
      name: "Bloemkool",
      variety: "HerfstReuzen 2",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 1,
    },
    {
      id: crypto.randomUUID(),
      name: "Palmkool",
      variety: "Nero di Toscana",
      sowFrom: Month.April,
      sowTill: Month.June,
      plantFrom: Month.April,
      plantTill: Month.June,
      plantHeight: PlantHeight.MEDIUM,
      numberOfSeedsPerGridCell: 1,
    },
  ] as SeedDTO[];

  const bed: BedDTO = {
    id: crypto.randomUUID(),
    name: "Voorbeeldbed",
    sowDate: "2022-03-01",
    gridWidth: 5,
    gridHeight: 5,
  } as BedDTO;

  const _gridItem: GridItemDTO = {
    index: 1,
    seedId: februarySeeds[0].id,
    bedId: bed.id,
  };

  await db.insert(usersTable).values(user);
  console.log("New user created!");

  for (const seed of februarySeeds) {
    await db.insert(seedsTable).values(seed);
  }
  console.log("February seeds created!");

  for (const seed of marchSeeds) {
    await db.insert(seedsTable).values(seed);
  }
  console.log("March seeds created!");

  for (const seed of aprilSeeds) {
    await db.insert(seedsTable).values(seed);
  }
  console.log("April seeds created!");

  // await db.insert(bedTable).values(bed);
  // console.log("New bed created!");
  //
  // await db.insert(gridItemTable).values(gridItem);
  // console.log("New grid item created!");
};

main();
